apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  replicas: 2  # Number of replicas for your application
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: abhivajani/todo-app1:latest  # Your Docker Hub image
          ports:
            - containerPort: 80  # The port exposed by the container
