apiVersion: v1
kind: Service
metadata:
  name: todo-app
spec:
  type: LoadBalancer  # Change to NodePort if you don't have a cloud provider
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: todo-app